sudo: required
services:
- docker
before_script:
- sudo /etc/init.d/postgresql stop
- docker-compose build
- docker-compose run web bundle exec rails db:test:prepare
script:
- docker-compose run web rspec
after_success:
- docker login -u _ -p "$HEROKU_TOKEN" registry.heroku.com
- docker build -t registry.heroku.com/imi-courses/web .
- docker push registry.heroku.com/imi-courses/web