version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/courseR
    ports:
      - "3000:3000"
    depends_on:
      - db